default: 
  mongo:
    db: 'mongodb://s2g-server:share2give@oceanic.mongohq.com:10094/roquefort'
  server:
    port: 8000
    cluster: false
  logs:
    # log directory
    dir: logs
    # for valid log levels, see [bunyan docs](https://github.com/trentm/node-bunyan#levels)
    level: debug
production:
  server:
    cluster: true
  logs:
    level: info
 # a.k.a integration- this tests all dependant system
test:       
  server:
    port: 8123
  logs:
    stream:
      level: warn
# development has only localhost network dependencies. Meant for lean and mean dev cycle.      
development: 
  server:
    port: 8123
  mongo:
    db: 'mongodb://localhost'
  logs:
    stream:
      level: warn
heroku:
  server:
    cluster: true
  logs:
    stream:
      level: info


